services:
    etm_system_soap_client_factory:
        class: ETM\AppBundle\Soap\ETMSystemSoapClientFactory
        arguments:
            - %soap_client.wsdl%
            - %soap_client.cert%
            - %soap_client.key%
